import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Category from '../components/Category'
import axios from 'axios'

export default function Home({categories}) {
  console.log(categories);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Category categories={categories}/>
    </div>
  )
}


export async function getStaticProps(){
    const res =await axios(`https://api.chucknorris.io/jokes/categories`)
    const categories =res.data;

    return {
        props:{categories}
    }
}